name: Aggregate GitHub Org and User Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_USER: "soodoku"
      ORG_LIST: "USER, gojiplus, in-rolls, appeler, matmulai, themains, finite-sample, geosensing, notnews, outside-edge" 
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python -m pip install requests

      - run: python src/main.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stats.json stats.md
          git commit -m "Update aggregated GitHub stats" || echo "No changes"
          git push
