name: Aggregate Organization Stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  aggregate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run Aggregator Action
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_OUTPUT_FORMAT: "JSON"
          GITHUB_ACTOR: ${{ github.actor }}
        run: python src/main.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add stats.json stats.md
          git commit -m "Update organization stats [automated]" || echo "No changes to commit"
          git push
